### ISSUE TITLE
Exception thrown from dotify formatter

### ISSUE THREAD

**Issue by josteinaj** [joeha480/dotify#178]
On the latest version of NLBs script I'm getting this exception when testing locally:

```
java.lang.RuntimeException: com.xmlcalabash.core.XProcException: java.lang.RuntimeException: Error while reformatting.
        at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:246) ~[na:na]
        at org.daisy.pipeline.job.Job.run(Job.java:216) ~[na:na]
        at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:110) ~[na:na]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66-internal]
Caused by: com.xmlcalabash.core.XProcException: java.lang.RuntimeException: Error while reformatting.
        at org.daisy.pipeline.braille.dotify.calabash.impl.OBFLToPEFStep.run(OBFLToPEFStep.java:104) ~[na:na]
        at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipelineCall.run(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
        at com.xmlcalabash.extensions.Eval.run(Unknown Source) ~[na:na]
        at org.daisy.pipeline.braille.common.calabash.impl.PxTransformStep.run(PxTransformStep.java:143) ~[na:na]
        at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipelineCall.run(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipelineCall.run(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
        at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:242) ~[na:na]
        ... 3 common frames omitted
Caused by: java.lang.RuntimeException: Error while reformatting.
        at org.daisy.dotify.formatter.impl.FormatterImpl.getVolumes(FormatterImpl.java:149) ~[na:na]
        at org.daisy.dotify.formatter.impl.FormatterImpl.write(FormatterImpl.java:125) ~[na:na]
        at org.daisy.dotify.obfl.ObflParser.writeResult(ObflParser.java:1460) ~[na:na]
        at org.daisy.dotify.engine.impl.LayoutEngineImpl.convert(LayoutEngineImpl.java:117) ~[na:na]
        at org.daisy.pipeline.braille.dotify.calabash.impl.OBFLToPEFStep.run(OBFLToPEFStep.java:93) ~[na:na]
        ... 22 common frames omitted
Caused by: org.daisy.dotify.formatter.impl.PaginatorException: Cannot fit ???????????????????????? into a margin-region of size 2
        at org.daisy.dotify.formatter.impl.PageSequenceBuilder2.getMarginRegionValue(PageSequenceBuilder2.java:316) ~[na:na]
        at org.daisy.dotify.formatter.impl.PageSequenceBuilder2.paginate(PageSequenceBuilder2.java:257) ~[na:na]
        at org.daisy.dotify.formatter.impl.PageStructBuilder.newSequence(PageStructBuilder.java:37) ~[na:na]
        at org.daisy.dotify.formatter.impl.PageStructBuilder.paginate(PageStructBuilder.java:24) ~[na:na]
        at org.daisy.dotify.formatter.impl.FormatterImpl.getVolumes(FormatterImpl.java:147) ~[na:na]
        ... 26 common frames omitted
```

Does this look like a Dotify problem?

**Comment by joeha480** [comment]
Difficult to say of course, but I'd first try to debug the css conversion, because the error message say's the margin region contains too much data, which is a deliberate error condition (i.e. checked for and manually thrown).

Maybe you have defined too many indicators, or maybe they have long values? I can have a look if you send me the OBFL. @bertfrees Is it possible to get the OBFL intermediary from the script?

**Comment by bertfrees** [comment]
Sure. I log the OBFL (with TRACE level).

I agree with Joel. It's important to check the OBFL first because I'm not sure what I generate is valid. Does Dotify do any validation? Otherwise maybe I should add a validation step after the css-to-obfl step.

**Comment by joeha480** [comment]
I left the OBFL validation out of the formatter back when we first started with the Pipeline integration. It would be nice if we can cooperate on the validation step, because I do validation after my conversion to OBFL as well. In it however, it only reports the violations, it doesn't stop the process.

Note that this particular problem wouldn't be caught by the validator though. The best I can think of is improving the error message. Ideally I would like to be able to point to something in the input xml, but it's a long way to get there. However, if you can get to what's behind the question marks in the trace (it should be unicode braille in the original stacktrace, but it has been lost in the web UI or when you copied it here). If you read the unicode braille, you should be able to pinpoint the indicators that is causing a problem.

**Comment by josteinaj** [comment]
So the intermediary format that is mentioned in the requirements, that's OBFL, right? Does that mean it should be exposed as a downloadable file in the scripts?

**Comment by bertfrees** [comment]
An option to download the OBFL is something I want to add this month. But I'm not sure it's a requirement for this particular issue. Because if you have the OBFL and an error message saying where things have gone wrong, you still don't know what to do to fix things in the source document. But on the other hand it doesn't hurt and it could be a help for the developers if there is a bug to be fixed.
